name: Nova CI-Rescue Demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

jobs:
  test-and-auto-fix:
    runs-on: ubuntu-latest
    environment: Secrets
    permissions:
      contents: write # For pushing fixes
      pull-requests: write # For creating PRs
      issues: write # For commenting on issues

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better diff generation

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-json-report

      - name: Run initial tests
        id: initial-tests
        continue-on-error: true
        run: |
          echo "Running initial test suite..."
          pytest tests/ -v --tb=short > test_results.txt 2>&1 || echo "TESTS_FAILED=true" >> $GITHUB_OUTPUT
          cat test_results.txt

      - name: Install Nova CI-Rescue if tests failed
        if: steps.initial-tests.outputs.TESTS_FAILED == 'true'
        run: |
          echo "Installing Nova CI-Rescue..."
          pip install --no-cache-dir --force-reinstall git+https://github.com/novasolve/ci-auto-rescue.git@demo

      - name: Configure Git for commits
        if: steps.initial-tests.outputs.TESTS_FAILED == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions (Nova CI-Rescue)"

      - name: Run Nova Auto-Fix if tests failed
        if: steps.initial-tests.outputs.TESTS_FAILED == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Use GPT-5 for main operations, GPT-4o for PR generation
          NOVA_DEFAULT_LLM_MODEL: gpt-5
          NOVA_PR_LLM_MODEL: gpt-4.1
        run: |
          echo "Tests failed! Running Nova CI-Rescue to auto-fix..."
          nova fix . --ci

      - name: Push Nova's fixes back to PR
        if: steps.initial-tests.outputs.TESTS_FAILED == 'true'
        run: |
          # Check if Nova made any changes
          if [ -n "$(git status --porcelain)" ] || [ -n "$(git diff HEAD^ HEAD --name-only 2>/dev/null)" ]; then
            echo "Nova made changes, pushing to PR..."
            git push origin HEAD:${{ github.head_ref }}
            echo "✅ Pushed Nova's fixes to PR"
          else
            echo "No changes to push"
          fi

      - name: Run tests after fix
        if: steps.initial-tests.outputs.TESTS_FAILED == 'true'
        run: |
          echo "Running tests after Nova fix..."
          pytest tests/ -v

      - name: Upload Nova artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nova-artifacts
          path: |
            .nova/
            *.log
            nova-*.log
            telemetry/
          retention-days: 7
          if-no-files-found: ignore
